sonar.projectKey=CI-CD_Soner
sonar.projectName=CI-CD_Soner

sonar.sources=.
#sonar.sources=src
#sonar.tests=test

#sonar.c.file.suffixes=.c
#sonar.cfamily.file.suffixes=.c,.h

#sonar.exclusions=build/**,gcov/**
sonar.sourceEncoding=UTF-8

sonar.cxx.file.suffixes=.h,.c
