sonar.projectKey=CI-CD_Soner
sonar.projectName=CI-CD_Soner

# Only analyze source and test folders
sonar.sources=src
sonar.tests=test

# Only include C/C++ files
sonar.inclusions=src/**/*.c,src/**/*.h,test/**/*.c,test/**/*.h

# Exclude everything else
sonar.exclusions=build/**,.github/**,README.md,project.yml

sonar.sourceEncoding=UTF-8
